#!/bin/bash
# Backup to hard drive
DIRS=( "$HOME/desk" "$HOME/dl" "$HOME/pdf" "keystore" )

set -e

drivers=$(lsblk -nrpo "name,type,size,mountpoint" | awk '$2=="part"&&$4!~/\/boot|\/home$|SWAP/&&length($4)>1{printf "%s (%s)\n",$4,$3}')

[ -z "$drivers" ] && echo "No mounted drives found" && exit

DESTINATION=$(echo "$drivers" | fzf --prompt="Backup destination: ")
DESTINATION=$(echo "$DESTINATION" | awk '{print $1}')
echo $DESTINATION



tar -cvPpzf "$DESTINATION/$(date +'bkp_%d-%m-%Y_%I-%M').tar.gz"  "${DIRS[@]}"
echo "Success"
