#!/bin/sh
# Give a battery name (e.g. BAT0) as an argument.

# get xresources color
# # "s/*(.*)\./export /g;s/:\s*/=\"/g;s/$/\"/g")"
for x in "$(xrdb -query | grep color | sed "s/\*color\([0-9]*\):\s*#\([0-9a-fA-F]*\)/color\1=\"#\2\"/g")" ; do eval "$x"; done

case $BLOCK_BUTTON in
	3) pgrep -x dunst >/dev/null && notify-send "<b> Battery module:</b>
		: not charging
		: stagnant charge
		: charging
		: battery very low!
		" ;;
esac

capacity=$(cat /sys/class/power_supply/"$1"/capacity) || exit
status=$(cat /sys/class/power_supply/"$1"/status)

if [ "$capacity" -ge 75 ]; then
	color="$color10"
elif [ "$capacity" -ge 50 ]; then
	color="$color15"
elif [ "$capacity" -ge 25 ]; then
	color="$color11"
else
	color="$color9"
fi

[ "$status" = "Charging" ] && color="$color15"

case $(echo "$status" | sed -e "s/,//") in
	Discharging)
		ic_list=("" "" "" "" "")
		# ic_list=("" "" "" "" "" "" "" "" "" "")
		nof_icons="${#ic_list[@]}"
		ic_index=$(($capacity * $nof_icons / 100))
		ic_index=$(($ic_index==$nof_icons?$nof_icons-1:$ic_index))

		icon="${ic_list[$ic_index]}"
		;;
	Not\ Charging)
		icon=""
		;;
	Charging)
		ic_list=("" "" "" "" "" "" "")
		nof_icons="${#ic_list[@]}"
		ic_index=$(($capacity * $nof_icons / 100))
		ic_index=$(($ic_index==$nof_icons?$nof_icons-1:$ic_index))

		icon="${ic_list[$ic_index]}"
		;;
	Unknown)
		icon=""
		;;
	Full)
		icon=""
		;;

	esac



	printf "<span color='%s'>%s %s</span>" \
		"$color" \
		"$icon"\
		"$(echo "$capacity" | sed -e 's/$/%/')"
